### ISSUE TITLE
Attach the binary files

### ISSUE THREAD

**Issue by withanage** [kadowa/omp-xmdp-oai-plugin#1]
has to be discussed, how the attachement should be done.

**Comment by kadowa** [comment]
Similar to here? http://files.dnb.de/standards/xmetadissplus/kurzbeispiel_xmetadiss.xml

**Comment by withanage** [comment]
yes, I would  extend the file field like that. Best, would be to add a relative file path. If it is not possible, we wave to code as they have in the example.

**Comment by kadowa** [comment]
This is an issue for the metadata plugin, not the OAI interface. See https://github.com/kadowa/omp-xmdp-metadata-plugin/issues/2.
